insert into locations values (111,'New York City, USA')
insert into locations values (112,'Los Angeles, USA')
insert into locations values (113,'Paris, France')
insert into locations values (114,'London, UK')
insert into locations values (115,'Tokyo, Japan')
insert into locations values (116,'Sydney, Australia')
insert into locations values (117,'Hong Kong, China')
insert into locations values (118,'Rome, Italy')
insert into locations values (119,'Barcelona, Spain')
insert into locations values (120,'Dubai, UAE')
insert into locations values (121,'Singapore')
insert into locations values (122,'Moscow, Russia')
insert into locations values (123,'Rio de Janeiro, Brazil')
insert into locations values (124,'Toronto, Canada')
insert into locations values (125,'Amsterdam, Netherlands')
insert into locations values (126,'Berlin, Germany')
insert into locations values (127,'Mumbai, India')
insert into locations values (128,'Buenos Aires, Argentina')
insert into locations values (129,'Shanghai, China')
insert into locations values (130,'Istanbul, Turkey')
insert into locations values (131,'San Francisco, USA')
insert into locations values (132,'Miami, USA')
insert into locations values (133,'Prague, Czech Republic')
insert into locations values (134,'Athens, Greece')
insert into locations values (135,'Seoul, South Korea')
insert into locations values (136,'Edinburgh, Scotland')
insert into locations values (137,'Vancouver, Canada')
insert into locations values (138,'Copenhagen, Denmark')
insert into locations values (139,'Stockholm, Sweden')
insert into locations values (140,'Lisbon, Portugal')
insert into locations values (141,'Budapest, Hungary')
insert into locations values (142,'Vienna, Austria')
insert into locations values (143,'Warsaw, Poland')
insert into locations values (144,'Zurich, Switzerland')
insert into locations values (145,'Helsinki, Finland')
insert into locations values (146,'Oslo, Norway')
insert into locations values (147,'Brussels, Belgium')
insert into locations values (148,'Dublin, Ireland')
insert into locations values (149,'Kiev, Ukraine')
insert into locations values (150,'Bucharest, Romania')
insert into locations values (151,'Jakarta, Indonesia')
insert into locations values (152,'Cairo, Egypt')
insert into locations values (153,'Cape Town, South Africa')
insert into locations values (154,'Marrakech, Morocco')
insert into locations values (155,'Bangkok, Thailand')
insert into locations values (156,'Hanoi, Vietnam')
insert into locations values (157,'Ho Chi Minh City, Vietnam')
insert into locations values (158,'Kuala Lumpur, Malaysia')
insert into locations values (159,'Taipei, Taiwan')
insert into locations values (160,'Phnom Penh, Cambodia')
insert into locations values (161,'Manila, Philippines')
insert into locations values (162,'Dhaka, Bangladesh')
insert into locations values (163,'Kathmandu, Nepal')
insert into locations values (164,'Colombo, Sri Lanka')
insert into locations values (165,'Santiago, Chile')
insert into locations values (166,'Bogota, Colombia')
insert into locations values (167,'Lima, Peru')
insert into locations values (168,'Quito, Ecuador')
insert into locations values (169,'Caracas, Venezuela')
insert into locations values (170,'San Juan, Puerto Rico')
insert into locations values (171,'Havana, Cuba')
insert into locations values (172,'San Salvador, El Salvador')
insert into locations values (173,'Tegucigalpa, Honduras')
insert into locations values (174,'Guatemala City, Guatemala')
insert into locations values (175,'Mexico City, Mexico')
insert into locations values (176,'Monterrey, Mexico')
insert into locations values (177,'Cancun, Mexico')
insert into locations values (178,'Acapulco, Mexico')
insert into locations values (179,'Tijuana, Mexico')
insert into locations values (180,'Vancouver Island, Canada')
insert into locations values (181,'Whistler, Canada')
insert into locations values (182,'Banff, Canada')
insert into locations values (183,'Jasper, Canada')
insert into locations values (184,'Halifax, Canada')
insert into locations values (185,'Ottawa, Canada')
insert into locations values (186,'Quebec City, Canada')
insert into locations values (187,'St John`s, Canada')
insert into locations values (188,'Reykjavik, Iceland')
insert into locations values (189,'Abu Dhabi, UAE')
insert into locations values (190,'Muscat, Oman')
insert into locations values (191,'Doha, Qatar')
insert into locations values (192,'Amman, Jordan')
insert into locations values (193,'Beirut, Lebanon')
insert into locations values (194,'Tel Aviv, Israel')
insert into locations values (195,'Jerusalem, Israel')
insert into locations values (196,'Petra, Jordan')
insert into locations values (197,'Luxor, Egypt')
insert into locations values (198,'Giza, Egypt')
insert into locations values (199,'Casablanca, Morocco')
insert into locations values (200,'Rabat, Morocco')
insert into locations values (201,'Fez, Morocco')
