insert into companies values (11,'Luminate Solutions','New York City, USA',0)
insert into companies values (12,'Nimbus Innovations','Los Angeles, USA',0)
insert into companies values (13,'Stellar Strategies','Paris, France',0)
insert into companies values (14,'Quantum Dynamics','London, UK',0)
insert into companies values (15,'Vantage Ventures','Tokyo, Japan',0)
insert into companies values (16,'Helix Enterprises','Sydney, Australia',0)
insert into companies values (17,'Apex Analytics','Hong Kong, China',0)
insert into companies values (18,'Zenith Industries','Rome, Italy',0)
insert into companies values (19,'Catalyst Concepts','Barcelona, Spain',0)
insert into companies values (20,'Phoenix Group','Dubai, UAE',0)
insert into companies values (21,'NovaTech Solutions','Singapore',0)
insert into companies values (22,'Summit Synergy','Moscow, Russia',0)
insert into companies values (23,'Precision Partners','Rio de Janeiro, Brazil',0)
insert into companies values (24,'Momentum Marketing','Toronto, Canada',0)
insert into companies values (25,'Synergy Systems','Amsterdam, Netherlands',0)
insert into companies values (26,'Fusion Five','Berlin, Germany',0)
insert into companies values (27,'Infinity Innovations','Mumbai, India',0)
insert into companies values (28,'Spectrum Solutions','Buenos Aires, Argentina',0)
insert into companies values (29,'Vertex Ventures','Shanghai, China',0)
insert into companies values (30,'Arcadian Analytics','Istanbul, Turkey',0)

select * from companies