insert into issues values (111,'Billing and payment issues')
insert into issues values (112,'Technical difficulties with a product or service')
insert into issues values (113,'Difficulty navigating a website or app')
insert into issues values (114,'Inquiries about product availability or delivery status')
insert into issues values (115,'Issues with account access or login credentials')
insert into issues values (116,'Product malfunctions or defects')
insert into issues values (117,'Problems with the quality or functionality of a product')
insert into issues values (118,'Returns and exchanges')
insert into issues values (119,'Difficulty understanding or using a product or service')
insert into issues values (120,'Customer service complaints or dissatisfaction with a previous experience')
insert into issues values (121,'Problems with shipping or receiving a product')
insert into issues values (122,'Difficulty cancelling or modifying an order')
insert into issues values (123,'Issues with refunds or billing discrepancies')
insert into issues values (124,'Trouble using a coupon or discount code')
insert into issues values (125,'Inquiries about product warranties or guarantees')
insert into issues values (126,'Technical support for a product or service')
insert into issues values (127,'Difficulty accessing or using a product manual or instructions')
insert into issues values (128,'Reporting a lost or stolen product')
insert into issues values (129,'Inquiries about product compatibility with other devices or systems')
insert into issues values (130,'Questions about product or service pricing or promotions')
